In [224]:
from selenium import webdriver

In [225]:
from selenium.webdriver.common.by import By
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [226]:
from time import sleep

In [227]:
driver = webdriver.Chrome(r'C:\Users\shail\Downloads\chromedriver_win32\chromedriver.exe')

In [228]:
url = 'https://www.flipkart.com/'
driver.get(url)

In [229]:
search_sneakers = driver.find_element(By.CLASS_NAME,"_3704LK")
search_sneakers

In [230]:
search_sneakers.send_keys("sneakers")

In [231]:
search_btn = driver.find_element(By.XPATH,"/html/body/div[1]/div/div[1]/div[1]/div[2]/div[2]/form/div/button")
search_btn

In [232]:
search_btn.click()

In [233]:
brand = []
for i in range(3):
    print('Scraping page',i+1)
    brands_name = driver.find_elements(By.XPATH,'//div[@class="_2B099V"]')
    for b in brands_name:
        brand.append(b.text)
    next_button = driver.find_element(By.XPATH,'//a[@class="_1LKTO3"]')    
    next_button.click()
    sleep(3)

Scraping page 1
Scraping page 2
Scraping page 3

In [234]:
len(brand)

120

In [235]:
brand

['Sumohan\nSneakers For Men\n₹499₹99950% off\nFree delivery',
 'U.S. POLO ASSN.\nClarkin 2.0 Sneakers For Men\n₹1,949₹2,99935% off\nFree delivery',
 'WOODLAND\nSneakers For Men\n₹1,797₹2,99540% off\nFree delivery\nEOSS',
 'BRUTON\nModern Trendy Sneakers Shoes Sneakers For Men\n₹284₹1,29978% off\nFree delivery\nDeal of the Day',
 'SFR\nSneakers For Men\n₹289₹99971% off\nFree delivery',
 'URBANBOX\nSneakers Sneakers For Men\n₹219₹99978% off\nFree delivery',
 'PUMA\nPuma Smash v2 L Sneakers For Men\n₹1,658₹3,49952% off\nFree delivery\nEOSS',
 'RapidBox\nStylish & Trendy Sneakers For Men\n₹610₹99938% off\nFree delivery',
 'aadi\nSneakers For Men\n₹359₹99964% off\nFree delivery\nDeal of the Day',
 'KWIK FIT\nKwik FIT casual sneaker shoes and partywear shoes Casua...\n₹449₹1,99977% off\nFree delivery',
 'BRUTON\nModern Trendy Sneakers Shoes Sneakers For Men\n₹299₹1,29976% off\nFree delivery\nDeal of the Day',
 'ZF - ALFIYA\nSneakers For Men\n₹449₹99955% off\nFree delivery',
 "ASTEROID\nOriginal Luxury Branded Fashionable Men's Casual Walkin...\n₹474₹1,99976% off\nFree delivery\nDeal of the Day",
 'aadi\nSneakers For Men\n₹299₹99970% off\nFree delivery\nDeal of the Day',
 'Kraasa\nShark-41 Sneakers For Men\n₹539₹99946% off\nFree delivery\nDeal of the Day',
 'RapidBox\nSneakers For Men\n₹630₹99936% off\nFree delivery',
 'Labbin\nSneakers For Men\n₹449₹99955% off\nFree delivery',
 'Magnolia\nSneakers For Men\n₹449₹99955% off\nFree delivery\nDeal of the Day',
 'Kraasa\nCasuals, Canvas, Partywear Sneakers For Men\n₹539₹99946% off\nFree delivery\nDeal of the Day',
 'HRX by Hrithik Roshan\nSneakers For Men\n₹1,784₹2,99940% off\nFree delivery',
 'BIRDE\nStylish Comfortable Lightweight, Breathable Walking Sho...\n₹398₹99960% off\nFree delivery\nDeal of the Day',
 'Kzaara\nSneakers For Men\n₹254₹99974% off\nFree delivery',
 'BIRDE\nStylish Comfortable Lightweight, Breathable Walking Sho...\n₹442₹99955% off\nFree delivery',
 'U.S. POLO ASSN.\nSneakers For Men\n₹2,079₹3,19935% off\nFree delivery',
 'Dizzler\nSneakers For Men\n₹435₹71939% off\nFree delivery',
 'AMICO\nSneakers For Men\n₹494₹99950% off\nFree delivery\nDeal of the Day',
 'Chevit\nSuper Stylish & Trendy Combo Pack of 02 Pairs Sneakers ...\n₹649₹1,89865% off\nFree delivery\nDeal of the Day',
 'KNIGHT WALKERS\nSS1100 Sneakers For Men\n₹664₹1,99966% off\nFree delivery\nBuy 2 items, save extra 5%',
 "Chevit\nMen's Combo Pack of 02 Shoes for Men Casual Sneakers Ou...\n₹466₹1,09957% off\nFree delivery\nDeal of the Day",
 'Noztile\nSneakers For Men\n₹414₹1,99979% off\nFree delivery\nLowest Price in 15 days',
 'ONECENTRE\nSTR2 Sneakers For Men\n₹299₹62051% off\nFree delivery',
 'U.S. POLO ASSN.\nCASTRO Sneakers For Men\n₹2,599₹3,99935% off\nFree delivery',
 'Rzisbo\nSneakers For Men\n₹464₹99953% off\nFree delivery\nDeal of the Day',
 'BRUTON\nLightweight Pack Of 1 Trendy Sneakers Sneakers For Men\n₹199₹59966% off\nFree delivery',
 'CLYMB\nSneakers For Men\n₹519₹1,49965% off\nFree delivery\nDeal of the Day',
 'U.S. POLO ASSN.\nTREGGER 2.0 Sneakers For Men\n₹2,989₹4,59935% off\nFree delivery\nEOSS',
 'luxury fashion\nLuxury Fashionable casual sneaker shoes Sneakers For Me...\n₹399₹1,29969% off\nFree delivery\nDeal of the Day',
 'PUMA\nPuma Smash v2 L Sneakers For Men\n₹1,784₹3,49949% off\nFree delivery\nEOSS',
 'ASTEROID\nOriginal Luxury Branded Black Fancy Casual Walking Part...\n₹474₹99952% off\nFree delivery\nDeal of the Day',
 'LAADSAHAB\nSneakers For Men Sneakers For Men\n₹599₹1,49960% off\nFree delivery',
 'HOTSTYLE\nSneakers For Men\n₹284₹99871% off\nFree delivery',
 'AMICO\nSneakers For Men\n₹494₹99950% off\nFree delivery\nDeal of the Day',
 'corsac\nSTYLISH MENS BLACK SNEAKER Sneakers For Men\n₹474₹1,49968% off\nFree delivery',
 'FLOREX\nFlorex Casual Premium quality Party Wear Canvas Sneaker...\n₹499₹99950% off\nFree delivery',
 'Numenzo\n411 Casual Sneakers For Men\n₹402₹1,99979% off\nFree delivery\nDeal of the Day',
 "Shoes Bank\nWhite Sneaker For Men's/Boy's Sneakers For Men\n₹297₹99970% off\nFree delivery",
 'BRUTON\nExclusive Sneaker Shoes Sneakers For Men\n₹299₹1,29976% off\nFree delivery\nDeal of the Day',
 'RapidBox\nSneakers For Men\n₹630₹99936% off\nFree delivery',
 'Stinson\nSneakers For Men\n₹249₹49950% off\nFree delivery',
 'luxury fashion\nLuxury Fashionable casual sneaker shoes Sneakers For Me...\n₹379₹2,99987% off\nFree delivery\nDeal of the Day',
 "D-SNEAKERZ\nCasual , Partywear Sneakers Shoes For Men's And Boys Wh...\n₹299₹65954% off\nFree delivery",
 'Shoes Icon\nSneakers For Men\n₹399₹99960% off\nFree delivery',
 'India hub\nLuxury Fashionable casual sneaker shoes Sneakers For Me...\n₹397₹1,99980% off\nFree delivery\nDeal of the Day',
 'PUMA\nR78 Sneakers For Men\n₹2,339₹3,99941% off\nFree delivery\nDeal of the Day',
 'BIRDE\nStylish Comfortable Lightweight, Breathable Casual Walk...\n₹398₹99960% off\nFree delivery',
 'RapidBox\nSneakers For Men\n₹630₹99936% off\nFree delivery',
 'KNIGHT WALKERS\nSS1100 Sneakers For Men\n₹664₹1,99966% off\nFree delivery\nBuy 2 items, save extra 5%',
 'BRUTON\nSneaker Sneakers For Men\n₹284₹1,29978% off\nFree delivery\nDeal of the Day',
 'PUMA\nSmash v2 L White- Black Sneakers For Men\n₹1,854₹3,49947% off\nFree delivery\nEOSS',
 'Shoes Icon\nSneakers For Men\n₹439₹99956% off\nFree delivery',
 'Robbie jones\nCasual Sneakers White Shoes For Men Sneakers For Men\n₹449₹99955% off\nFree delivery',
 'Eiffel\nStylish & Comfortable Sneakers For Men\n₹469₹99953% off\nFree delivery',
 'SCATCHITE\nSneakers Sneakers For Men\n₹378₹99962% off\nFree delivery',
 'Numenzo\nSneakers For Men\n₹466₹1,29964% off\nFree delivery\nDeal of the Day',
 'Kraasa\nSeries 7 Sneakers For Men\n₹539₹99946% off\nFree delivery\nDeal of the Day',
 'Layasa\nSneakers For Men\n₹499₹99950% off\nFree delivery',
 'BIRDE\nSports Running Shoes Sneakers For Men\n₹353₹99864% off\nFree delivery\nDeal of the Day',
 'aadi\nSynthetic Leather Sneakers For Men\n₹599₹1,99970% off\nFree delivery',
 'PEXLO\nCombo Pack of 3 Casual Shoes Sneakers For Men\n₹707₹1,49752% off\nFree delivery\nDeal of the Day',
 'PUMA\nST Activate V2 Sneakers For Men\n₹1,469₹3,49958% off\nFree delivery\nDeal of the Day',
 'Magnolia\nSneakers For Men\n₹424₹99957% off\nFree delivery\nDeal of the Day',
 "Anugrahappradha\nW18 men's very comfortable casaul shoes Sneakers For Me...\n₹699₹2,99976% off\nFree delivery",
 'Magnolia\nSneakers For Men\n₹449₹99955% off\nFree delivery\nDeal of the Day',
 'URBANBOX\nSTYLISH-WHITE-6 Sneakers For Men\n₹179₹49964% off\nFree delivery',
 'Robbie jones\nCasual Sneakers Canvas Shoes For Men Sneakers For Men\n₹449₹99955% off\nFree delivery',
 'KWIK FIT\nCasual Trendy Fashion Sport Sneaker Shoes Gym Running P...\n₹499₹1,99975% off\nFree delivery',
 'BRUTON\nLattest Sneakers Shoe Sneakers For Men\n₹269₹1,29979% off\nFree delivery\nDeal of the Day',
 'Kzaara\nKzaara Sneakers Casual Canvas shoes | Branded Stylish O...\n₹244₹99975% off\nFree delivery',
 "SHOELAMB\nMen's White Casual Walking Running Sneaker Shoe Sneaker...\n₹683₹79914% off\nFree delivery",
 'Bacan\nSneakers For Men\n₹450₹99954% off\nFree delivery\nBuy 2 items, save extra 5%',
 'Scull Wings\ntrendy Sneakers For Men Sporty Sneakers For Men Fashion...\n₹499₹1,49966% off\nFree delivery',
 'Sumohan\nSneakers For Men\n₹499₹99950% off\nFree delivery',
 'WOODLAND\nSneakers For Men\n₹1,797₹2,99540% off\nFree delivery\nEOSS',
 'BRUTON\nModern Trendy Sneakers Shoes Sneakers For Men\n₹284₹1,29978% off\nFree delivery\nDeal of the Day',
 'PUMA\nPuma Smash v2 L Sneakers For Men\n₹1,658₹3,49952% off\nFree delivery\nEOSS',
 'SFR\nSneakers For Men\n₹289₹99971% off\nFree delivery',
 'URBANBOX\nSneakers Sneakers For Men\n₹219₹99978% off\nFree delivery',
 'U.S. POLO ASSN.\nClarkin 2.0 Sneakers For Men\n₹1,949₹2,99935% off\nFree delivery',
 'aadi\nSneakers For Men\n₹359₹99964% off\nFree delivery\nDeal of the Day',
 'BRUTON\nModern Trendy Sneakers Shoes Sneakers For Men\n₹299₹1,29976% off\nFree delivery\nDeal of the Day',
 "ASTEROID\nOriginal Luxury Branded Fashionable Men's Casual Walkin...\n₹474₹1,99976% off\nFree delivery\nDeal of the Day",
 'RapidBox\nStylish & Trendy Sneakers For Men\n₹610₹99938% off\nFree delivery',
 'KWIK FIT\nKwik FIT casual sneaker shoes and partywear shoes Casua...\n₹449₹1,99977% off\nFree delivery',
 'aadi\nSneakers For Men\n₹299₹99970% off\nFree delivery\nDeal of the Day',
 'Labbin\nSneakers For Men\n₹449₹99955% off\nFree delivery',
 'ZF - ALFIYA\nSneakers For Men\n₹449₹99955% off\nFree delivery',
 'Kraasa\nShark-41 Sneakers For Men\n₹539₹99946% off\nFree delivery\nDeal of the Day',
 'Magnolia\nSneakers For Men\n₹449₹99955% off\nFree delivery\nDeal of the Day',
 'Kraasa\nCasuals, Canvas, Partywear Sneakers For Men\n₹539₹99946% off\nFree delivery\nDeal of the Day',
 'RapidBox\nSneakers For Men\n₹630₹99936% off\nFree delivery',
 'BIRDE\nStylish Comfortable Lightweight, Breathable Walking Sho...\n₹398₹99960% off\nFree delivery\nDeal of the Day',
 'Kzaara\nSneakers For Men\n₹254₹99974% off\nFree delivery',
 'BIRDE\nStylish Comfortable Lightweight, Breathable Walking Sho...\n₹442₹99955% off\nFree delivery',
 'HRX by Hrithik Roshan\nSneakers For Men\n₹1,784₹2,99940% off\nFree delivery',
 'AMICO\nSneakers For Men\n₹494₹99950% off\nFree delivery\nDeal of the Day',
 'Dizzler\nSneakers For Men\n₹435₹71939% off\nFree delivery',
 "Chevit\nMen's Combo Pack of 02 Shoes for Men Casual Sneakers Ou...\n₹466₹1,09957% off\nFree delivery\nDeal of the Day",
 'STRANGER BROTHERS\nWhite & Black Sneakers For Men Casual Shoes For Men Tre...\n₹496₹1,49966% off\nFree delivery',
 'Chevit\nSuper Stylish & Trendy Combo Pack of 02 Pairs Sneakers ...\n₹649₹1,89865% off\nFree delivery\nDeal of the Day',
 'Noztile\nSneakers For Men\n₹414₹1,99979% off\nFree delivery\nLowest Price in 15 days',
 'CLYMB\nSneakers For Men\n₹519₹1,49965% off\nFree delivery\nDeal of the Day',
 'U.S. POLO ASSN.\nSneakers For Men\n₹2,079₹3,19935% off\nFree delivery',
 'Rzisbo\nSneakers For Men\n₹464₹99953% off\nFree delivery\nDeal of the Day',
 'ONECENTRE\nSTR2 Sneakers For Men\n₹299₹62051% off\nFree delivery',
 'BRUTON\nLightweight Pack Of 1 Trendy Sneakers Sneakers For Men\n₹199₹59966% off\nFree delivery',
 'KNIGHT WALKERS\nSS1100 Sneakers For Men\n₹664₹1,99966% off\nFree delivery\nBuy 2 items, save extra 5%',
 'luxury fashion\nLuxury Fashionable casual sneaker shoes Sneakers For Me...\n₹399₹1,29969% off\nFree delivery\nDeal of the Day',
 'PUMA\nPuma Smash v2 L Sneakers For Men\n₹1,784₹3,49949% off\nFree delivery\nEOSS',
 'ASTEROID\nOriginal Luxury Branded Black Fancy Casual Walking Part...\n₹474₹99952% off\nFree delivery\nDeal of the Day',
 'U.S. POLO ASSN.\nCASTRO Sneakers For Men\n₹2,599₹3,99935% off\nFree delivery']

In [236]:
b_n = brand[0:100]

In [237]:
b_n

['Sumohan\nSneakers For Men\n₹499₹99950% off\nFree delivery',
 'U.S. POLO ASSN.\nClarkin 2.0 Sneakers For Men\n₹1,949₹2,99935% off\nFree delivery',
 'WOODLAND\nSneakers For Men\n₹1,797₹2,99540% off\nFree delivery\nEOSS',
 'BRUTON\nModern Trendy Sneakers Shoes Sneakers For Men\n₹284₹1,29978% off\nFree delivery\nDeal of the Day',
 'SFR\nSneakers For Men\n₹289₹99971% off\nFree delivery',
 'URBANBOX\nSneakers Sneakers For Men\n₹219₹99978% off\nFree delivery',
 'PUMA\nPuma Smash v2 L Sneakers For Men\n₹1,658₹3,49952% off\nFree delivery\nEOSS',
 'RapidBox\nStylish & Trendy Sneakers For Men\n₹610₹99938% off\nFree delivery',
 'aadi\nSneakers For Men\n₹359₹99964% off\nFree delivery\nDeal of the Day',
 'KWIK FIT\nKwik FIT casual sneaker shoes and partywear shoes Casua...\n₹449₹1,99977% off\nFree delivery',
 'BRUTON\nModern Trendy Sneakers Shoes Sneakers For Men\n₹299₹1,29976% off\nFree delivery\nDeal of the Day',
 'ZF - ALFIYA\nSneakers For Men\n₹449₹99955% off\nFree delivery',
 "ASTEROID\nOriginal Luxury Branded Fashionable Men's Casual Walkin...\n₹474₹1,99976% off\nFree delivery\nDeal of the Day",
 'aadi\nSneakers For Men\n₹299₹99970% off\nFree delivery\nDeal of the Day',
 'Kraasa\nShark-41 Sneakers For Men\n₹539₹99946% off\nFree delivery\nDeal of the Day',
 'RapidBox\nSneakers For Men\n₹630₹99936% off\nFree delivery',
 'Labbin\nSneakers For Men\n₹449₹99955% off\nFree delivery',
 'Magnolia\nSneakers For Men\n₹449₹99955% off\nFree delivery\nDeal of the Day',
 'Kraasa\nCasuals, Canvas, Partywear Sneakers For Men\n₹539₹99946% off\nFree delivery\nDeal of the Day',
 'HRX by Hrithik Roshan\nSneakers For Men\n₹1,784₹2,99940% off\nFree delivery',
 'BIRDE\nStylish Comfortable Lightweight, Breathable Walking Sho...\n₹398₹99960% off\nFree delivery\nDeal of the Day',
 'Kzaara\nSneakers For Men\n₹254₹99974% off\nFree delivery',
 'BIRDE\nStylish Comfortable Lightweight, Breathable Walking Sho...\n₹442₹99955% off\nFree delivery',
 'U.S. POLO ASSN.\nSneakers For Men\n₹2,079₹3,19935% off\nFree delivery',
 'Dizzler\nSneakers For Men\n₹435₹71939% off\nFree delivery',
 'AMICO\nSneakers For Men\n₹494₹99950% off\nFree delivery\nDeal of the Day',
 'Chevit\nSuper Stylish & Trendy Combo Pack of 02 Pairs Sneakers ...\n₹649₹1,89865% off\nFree delivery\nDeal of the Day',
 'KNIGHT WALKERS\nSS1100 Sneakers For Men\n₹664₹1,99966% off\nFree delivery\nBuy 2 items, save extra 5%',
 "Chevit\nMen's Combo Pack of 02 Shoes for Men Casual Sneakers Ou...\n₹466₹1,09957% off\nFree delivery\nDeal of the Day",
 'Noztile\nSneakers For Men\n₹414₹1,99979% off\nFree delivery\nLowest Price in 15 days',
 'ONECENTRE\nSTR2 Sneakers For Men\n₹299₹62051% off\nFree delivery',
 'U.S. POLO ASSN.\nCASTRO Sneakers For Men\n₹2,599₹3,99935% off\nFree delivery',
 'Rzisbo\nSneakers For Men\n₹464₹99953% off\nFree delivery\nDeal of the Day',
 'BRUTON\nLightweight Pack Of 1 Trendy Sneakers Sneakers For Men\n₹199₹59966% off\nFree delivery',
 'CLYMB\nSneakers For Men\n₹519₹1,49965% off\nFree delivery\nDeal of the Day',
 'U.S. POLO ASSN.\nTREGGER 2.0 Sneakers For Men\n₹2,989₹4,59935% off\nFree delivery\nEOSS',
 'luxury fashion\nLuxury Fashionable casual sneaker shoes Sneakers For Me...\n₹399₹1,29969% off\nFree delivery\nDeal of the Day',
 'PUMA\nPuma Smash v2 L Sneakers For Men\n₹1,784₹3,49949% off\nFree delivery\nEOSS',
 'ASTEROID\nOriginal Luxury Branded Black Fancy Casual Walking Part...\n₹474₹99952% off\nFree delivery\nDeal of the Day',
 'LAADSAHAB\nSneakers For Men Sneakers For Men\n₹599₹1,49960% off\nFree delivery',
 'HOTSTYLE\nSneakers For Men\n₹284₹99871% off\nFree delivery',
 'AMICO\nSneakers For Men\n₹494₹99950% off\nFree delivery\nDeal of the Day',
 'corsac\nSTYLISH MENS BLACK SNEAKER Sneakers For Men\n₹474₹1,49968% off\nFree delivery',
 'FLOREX\nFlorex Casual Premium quality Party Wear Canvas Sneaker...\n₹499₹99950% off\nFree delivery',
 'Numenzo\n411 Casual Sneakers For Men\n₹402₹1,99979% off\nFree delivery\nDeal of the Day',
 "Shoes Bank\nWhite Sneaker For Men's/Boy's Sneakers For Men\n₹297₹99970% off\nFree delivery",
 'BRUTON\nExclusive Sneaker Shoes Sneakers For Men\n₹299₹1,29976% off\nFree delivery\nDeal of the Day',
 'RapidBox\nSneakers For Men\n₹630₹99936% off\nFree delivery',
 'Stinson\nSneakers For Men\n₹249₹49950% off\nFree delivery',
 'luxury fashion\nLuxury Fashionable casual sneaker shoes Sneakers For Me...\n₹379₹2,99987% off\nFree delivery\nDeal of the Day',
 "D-SNEAKERZ\nCasual , Partywear Sneakers Shoes For Men's And Boys Wh...\n₹299₹65954% off\nFree delivery",
 'Shoes Icon\nSneakers For Men\n₹399₹99960% off\nFree delivery',
 'India hub\nLuxury Fashionable casual sneaker shoes Sneakers For Me...\n₹397₹1,99980% off\nFree delivery\nDeal of the Day',
 'PUMA\nR78 Sneakers For Men\n₹2,339₹3,99941% off\nFree delivery\nDeal of the Day',
 'BIRDE\nStylish Comfortable Lightweight, Breathable Casual Walk...\n₹398₹99960% off\nFree delivery',
 'RapidBox\nSneakers For Men\n₹630₹99936% off\nFree delivery',
 'KNIGHT WALKERS\nSS1100 Sneakers For Men\n₹664₹1,99966% off\nFree delivery\nBuy 2 items, save extra 5%',
 'BRUTON\nSneaker Sneakers For Men\n₹284₹1,29978% off\nFree delivery\nDeal of the Day',
 'PUMA\nSmash v2 L White- Black Sneakers For Men\n₹1,854₹3,49947% off\nFree delivery\nEOSS',
 'Shoes Icon\nSneakers For Men\n₹439₹99956% off\nFree delivery',
 'Robbie jones\nCasual Sneakers White Shoes For Men Sneakers For Men\n₹449₹99955% off\nFree delivery',
 'Eiffel\nStylish & Comfortable Sneakers For Men\n₹469₹99953% off\nFree delivery',
 'SCATCHITE\nSneakers Sneakers For Men\n₹378₹99962% off\nFree delivery',
 'Numenzo\nSneakers For Men\n₹466₹1,29964% off\nFree delivery\nDeal of the Day',
 'Kraasa\nSeries 7 Sneakers For Men\n₹539₹99946% off\nFree delivery\nDeal of the Day',
 'Layasa\nSneakers For Men\n₹499₹99950% off\nFree delivery',
 'BIRDE\nSports Running Shoes Sneakers For Men\n₹353₹99864% off\nFree delivery\nDeal of the Day',
 'aadi\nSynthetic Leather Sneakers For Men\n₹599₹1,99970% off\nFree delivery',
 'PEXLO\nCombo Pack of 3 Casual Shoes Sneakers For Men\n₹707₹1,49752% off\nFree delivery\nDeal of the Day',
 'PUMA\nST Activate V2 Sneakers For Men\n₹1,469₹3,49958% off\nFree delivery\nDeal of the Day',
 'Magnolia\nSneakers For Men\n₹424₹99957% off\nFree delivery\nDeal of the Day',
 "Anugrahappradha\nW18 men's very comfortable casaul shoes Sneakers For Me...\n₹699₹2,99976% off\nFree delivery",
 'Magnolia\nSneakers For Men\n₹449₹99955% off\nFree delivery\nDeal of the Day',
 'URBANBOX\nSTYLISH-WHITE-6 Sneakers For Men\n₹179₹49964% off\nFree delivery',
 'Robbie jones\nCasual Sneakers Canvas Shoes For Men Sneakers For Men\n₹449₹99955% off\nFree delivery',
 'KWIK FIT\nCasual Trendy Fashion Sport Sneaker Shoes Gym Running P...\n₹499₹1,99975% off\nFree delivery',
 'BRUTON\nLattest Sneakers Shoe Sneakers For Men\n₹269₹1,29979% off\nFree delivery\nDeal of the Day',
 'Kzaara\nKzaara Sneakers Casual Canvas shoes | Branded Stylish O...\n₹244₹99975% off\nFree delivery',
 "SHOELAMB\nMen's White Casual Walking Running Sneaker Shoe Sneaker...\n₹683₹79914% off\nFree delivery",
 'Bacan\nSneakers For Men\n₹450₹99954% off\nFree delivery\nBuy 2 items, save extra 5%',
 'Scull Wings\ntrendy Sneakers For Men Sporty Sneakers For Men Fashion...\n₹499₹1,49966% off\nFree delivery',
 'Sumohan\nSneakers For Men\n₹499₹99950% off\nFree delivery',
 'WOODLAND\nSneakers For Men\n₹1,797₹2,99540% off\nFree delivery\nEOSS',
 'BRUTON\nModern Trendy Sneakers Shoes Sneakers For Men\n₹284₹1,29978% off\nFree delivery\nDeal of the Day',
 'PUMA\nPuma Smash v2 L Sneakers For Men\n₹1,658₹3,49952% off\nFree delivery\nEOSS',
 'SFR\nSneakers For Men\n₹289₹99971% off\nFree delivery',
 'URBANBOX\nSneakers Sneakers For Men\n₹219₹99978% off\nFree delivery',
 'U.S. POLO ASSN.\nClarkin 2.0 Sneakers For Men\n₹1,949₹2,99935% off\nFree delivery',
 'aadi\nSneakers For Men\n₹359₹99964% off\nFree delivery\nDeal of the Day',
 'BRUTON\nModern Trendy Sneakers Shoes Sneakers For Men\n₹299₹1,29976% off\nFree delivery\nDeal of the Day',
 "ASTEROID\nOriginal Luxury Branded Fashionable Men's Casual Walkin...\n₹474₹1,99976% off\nFree delivery\nDeal of the Day",
 'RapidBox\nStylish & Trendy Sneakers For Men\n₹610₹99938% off\nFree delivery',
 'KWIK FIT\nKwik FIT casual sneaker shoes and partywear shoes Casua...\n₹449₹1,99977% off\nFree delivery',
 'aadi\nSneakers For Men\n₹299₹99970% off\nFree delivery\nDeal of the Day',
 'Labbin\nSneakers For Men\n₹449₹99955% off\nFree delivery',
 'ZF - ALFIYA\nSneakers For Men\n₹449₹99955% off\nFree delivery',
 'Kraasa\nShark-41 Sneakers For Men\n₹539₹99946% off\nFree delivery\nDeal of the Day',
 'Magnolia\nSneakers For Men\n₹449₹99955% off\nFree delivery\nDeal of the Day',
 'Kraasa\nCasuals, Canvas, Partywear Sneakers For Men\n₹539₹99946% off\nFree delivery\nDeal of the Day',
 'RapidBox\nSneakers For Men\n₹630₹99936% off\nFree delivery']

In [238]:
df1 = pd.DataFrame({'Product':b_n})

In [239]:
df1

                                              Product
0   Sumohan\nSneakers For Men\n₹499₹99950% off\nFr...
1   U.S. POLO ASSN.\nClarkin 2.0 Sneakers For Men\...
2   WOODLAND\nSneakers For Men\n₹1,797₹2,99540% of...
3   BRUTON\nModern Trendy Sneakers Shoes Sneakers ...
4   SFR\nSneakers For Men\n₹289₹99971% off\nFree d...
..                                                ...
95  ZF - ALFIYA\nSneakers For Men\n₹449₹99955% off...
96  Kraasa\nShark-41 Sneakers For Men\n₹539₹99946%...
97  Magnolia\nSneakers For Men\n₹449₹99955% off\nF...
98  Kraasa\nCasuals, Canvas, Partywear Sneakers Fo...
99  RapidBox\nSneakers For Men\n₹630₹99936% off\nF...

[100 rows x 1 columns]

In [240]:
f = df1['Product'].str.split(pat='\n',expand=True)
f

,0,1,2,3,4
0,Sumohan,Sneakers For Men,₹499₹99950% off,Free delivery,None
1,U.S. POLO ASSN.,Clarkin 2.0 Sneakers For Men,"₹1,949₹2,99935% off",Free delivery,None
2,WOODLAND,Sneakers For Men,"₹1,797₹2,99540% off",Free delivery,EOSS
3,BRUTON,Modern Trendy Sneakers Shoes Sneakers For Men,"₹284₹1,29978% off",Free delivery,Deal of the Day
4,SFR,Sneakers For Men,₹289₹99971% off,Free delivery,None
...,...,...,...,...,...
95,ZF - ALFIYA,Sneakers For Men,₹449₹99955% off,Free delivery,None
96,Kraasa,Shark-41 Sneakers For Men,₹539₹99946% off,Free delivery,Deal of the Day
97,Magnolia,Sneakers For Men,₹449₹99955% off,Free delivery,Deal of the Day
98,Kraasa,"Casuals, Canvas, Partywear Sneakers For Men",₹539₹99946% off,Free delivery,Deal of the Day
99,RapidBox,Sneakers For Men,₹630₹99936% off,Free delivery,None

In [241]:
df1['Name'] = f[0]
df1['Description'] = f[1]
df1['Price'] = f[2]
df1['Off'] = f[3]
df1['d'] = f[4]

In [242]:
df1.drop('Product',axis=1,inplace=True)
df1

,Name,Description,Price,Off,d
0,Sumohan,Sneakers For Men,₹499₹99950% off,Free delivery,None
1,U.S. POLO ASSN.,Clarkin 2.0 Sneakers For Men,"₹1,949₹2,99935% off",Free delivery,None
2,WOODLAND,Sneakers For Men,"₹1,797₹2,99540% off",Free delivery,EOSS
3,BRUTON,Modern Trendy Sneakers Shoes Sneakers For Men,"₹284₹1,29978% off",Free delivery,Deal of the Day
4,SFR,Sneakers For Men,₹289₹99971% off,Free delivery,None
...,...,...,...,...,...
95,ZF - ALFIYA,Sneakers For Men,₹449₹99955% off,Free delivery,None
96,Kraasa,Shark-41 Sneakers For Men,₹539₹99946% off,Free delivery,Deal of the Day
97,Magnolia,Sneakers For Men,₹449₹99955% off,Free delivery,Deal of the Day
98,Kraasa,"Casuals, Canvas, Partywear Sneakers For Men",₹539₹99946% off,Free delivery,Deal of the Day
99,RapidBox,Sneakers For Men,₹630₹99936% off,Free delivery,None

In [243]:
g = df1['Price'].str.split(pat='₹',expand=True)
g

   0       1             2
0        499    99950% off
1      1,949  2,99935% off
2      1,797  2,99540% off
3        284  1,29978% off
4        289    99971% off
.. ..    ...           ...
95       449    99955% off
96       539    99946% off
97       449    99955% off
98       539    99946% off
99       630    99936% off

[100 rows x 3 columns]

In [249]:
h = g[2].str[-7:]
h

0     50% off
1     35% off
2     40% off
3     78% off
4     71% off
       ...
95    55% off
96    46% off
97    55% off
98    46% off
99    36% off
Name: 2, Length: 100, dtype: object

In [245]:
df1['Price'] = g[1]

In [246]:
df1.drop('d',axis=1,inplace=True)
df1

,Name,Description,Price,Off
0,Sumohan,Sneakers For Men,499,Free delivery
1,U.S. POLO ASSN.,Clarkin 2.0 Sneakers For Men,"1,949",Free delivery
2,WOODLAND,Sneakers For Men,"1,797",Free delivery
3,BRUTON,Modern Trendy Sneakers Shoes Sneakers For Men,284,Free delivery
4,SFR,Sneakers For Men,289,Free delivery
...,...,...,...,...
95,ZF - ALFIYA,Sneakers For Men,449,Free delivery
96,Kraasa,Shark-41 Sneakers For Men,539,Free delivery
97,Magnolia,Sneakers For Men,449,Free delivery
98,Kraasa,"Casuals, Canvas, Partywear Sneakers For Men",539,Free delivery
99,RapidBox,Sneakers For Men,630,Free delivery

In [250]:
df1['Off'] = h

In [251]:
df1

,Name,Description,Price,Off
0,Sumohan,Sneakers For Men,499,50% off
1,U.S. POLO ASSN.,Clarkin 2.0 Sneakers For Men,"1,949",35% off
2,WOODLAND,Sneakers For Men,"1,797",40% off
3,BRUTON,Modern Trendy Sneakers Shoes Sneakers For Men,284,78% off
4,SFR,Sneakers For Men,289,71% off
...,...,...,...,...
95,ZF - ALFIYA,Sneakers For Men,449,55% off
96,Kraasa,Shark-41 Sneakers For Men,539,46% off
97,Magnolia,Sneakers For Men,449,55% off
98,Kraasa,"Casuals, Canvas, Partywear Sneakers For Men",539,46% off
99,RapidBox,Sneakers For Men,630,36% off